AWS_ACCESS_KEY_ID = '' # remove this if you have boto env variables set
AWS_SECRET_ACCESS_KEY = '' # remove this if you have boto env variables set
AWS_KEYPAIR = '' # remove this if you have boto env variables set
SERVER_USERNAME = '' # for ubuntu servers username is 'ubuntu' by default
SSH_PRIVATE_KEY_PATH = ''
INSTANCE_NAME_TAG = ''
AWS_AMIS = ['']
AWS_SECURITY = ['']
AWS_INSTANCE_TYPE = ''
AWS_REGION = ''